models:
  - n_estimators: 1000
    learning_rate: 0.03
    max_depth: 10
    min_child_weight: 5
    subsample: 0.8
    colsample_bytree: 0.8
    gamma: 0.0
    reg_alpha: 0.0
    reg_lambda: 1.0
    random_state: 42

  - n_estimators: 1000
    learning_rate: 0.03
    max_depth: -1
    num_leaves: 128
    min_child_samples: 20
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.0
    reg_lambda: 1.0
    verbosity: -1
    random_state: 42

  - iterations: 1000
    learning_rate: 0.03
    depth: 10
    loss_function: MAPE
    random_state: 42
    silent: True

